-- 1. Create referral_codes table
CREATE TABLE IF NOT EXISTS public.referral_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,
    agent_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_used BOOLEAN DEFAULT FALSE
);

-- 2. Add referred_by to users table
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS referred_by UUID REFERENCES public.users(id) ON DELETE SET NULL;

-- 3. RLS Policies for referral_codes

-- Enable RLS
-- Enable RLS
ALTER TABLE public.referral_codes ENABLE ROW LEVEL SECURITY;

-- Policy: Agents can see their own codes
DROP POLICY IF EXISTS "Agents can view their own codes" ON public.referral_codes;
CREATE POLICY "Agents can view their own codes" 
ON public.referral_codes FOR SELECT 
TO authenticated 
USING (auth.uid() = agent_id);

-- Policy: Agents can insert codes
DROP POLICY IF EXISTS "Agents can create codes" ON public.referral_codes;
CREATE POLICY "Agents can create codes" 
ON public.referral_codes FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = agent_id);

-- Policy: Public (Users) can select active codes to validate them
DROP POLICY IF EXISTS "Users can view valid codes" ON public.referral_codes;
CREATE POLICY "Users can view valid codes" 
ON public.referral_codes FOR SELECT 
TO authenticated 
USING (expires_at > now() AND is_used = FALSE);

-- Policy: Update (mark as used) - strictly done via Edge Function or secure RPC ideally
-- REQUIRED for the RPC to work? No, RPC uses SECURITY DEFINER.
-- But we'll keep this for completeness or fallback, dropping first.
DROP POLICY IF EXISTS "Users can mark code as used" ON public.referral_codes;
CREATE POLICY "Users can mark code as used" 
ON public.referral_codes FOR UPDATE 
TO authenticated 
USING (expires_at > now() AND is_used = FALSE)
WITH CHECK (is_used = TRUE);

-- Comments
COMMENT ON TABLE public.referral_codes IS 'Stores temporary referral codes generated by agents';
COMMENT ON COLUMN public.users.referred_by IS 'The Agent ID who referred this user';

-- 5. RLS for Users Table (Allow Agents to see their referrals)
-- Ensure RLS is enabled (it likely is, but good to be sure)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Agents can view referred users" ON public.users;
CREATE POLICY "Agents can view referred users" 
ON public.users FOR SELECT 
TO authenticated 
USING (referred_by = auth.uid());

-- 4. Secure Redemption Function (RPC)
-- (Rest of file...)
-- This function handles the entire redemption process atomically and securely, bypassing RLS issues.
CREATE OR REPLACE FUNCTION redeem_referral_code(code_input TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER -- Runs with permissions of the creator (admin), bypassing RLS
AS $$
DECLARE
  code_record RECORD;
BEGIN
  -- 1. Check if user is already referred (Optional: prevent double referral)
  -- IF EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND referred_by IS NOT NULL) THEN
  --   RAISE EXCEPTION 'User is already referred';
  -- END IF;

  -- 2. Find valid code
  SELECT * INTO code_record FROM public.referral_codes
  WHERE code = code_input AND is_used = FALSE AND expires_at > now();

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid or expired code';
  END IF;

  -- 3. Mark Code as Used
  UPDATE public.referral_codes 
  SET is_used = TRUE 
  WHERE id = code_record.id;

  -- 4. Link User to Agent
  UPDATE public.users 
  SET referred_by = code_record.agent_id 
  WHERE id = auth.uid();
END;
$$;
